# Project Bayes — Wednesday Case Walkthroughs (3 examples)

End-to-end pipeline grounded in three real PSI cases. Each example shows: the input the models saw, what they produced, the ground truth they were graded against, and how three independent judges scored each response.

Case selection rationale (filled in by `pick_wed_example_cases.py`):
- **Case 1** — both models score well (strong baseline)
- **Case 2** — models split (interesting differentiator)
- **Case 3** — both models struggle (where the benchmark is hard)

## Setup

In [1]:
import json
from pathlib import Path
import pandas as pd
from IPython.display import display, Markdown, HTML

pd.set_option("display.max_colwidth", None)

ARTIFACTS = Path("wed_examples_artifacts")

# Load the 3 hand-picked case artifacts (built by pick_wed_example_cases.py)
artifact_files = sorted(ARTIFACTS.glob("case_*.json"))
cases = [json.loads(p.read_text()) for p in artifact_files]
print(f"Loaded {len(cases)} hand-picked case artifacts:")
for i, c in enumerate(cases, 1):
    print(f"  {i}. {c['encounter_id'][:8]} | PSI={c['psi_code']} | {c['prompt_id']} | mean_score={c.get('mean_score', 'n/a')}")

Loaded 3 hand-picked case artifacts:
  1. FAB54B3F | PSI=PSI_15_ACCIDENTAL_PUNCTURE | C8 | mean_score=0.4
  2. 3F10EE61 | PSI=PSI_05_RETAINED_ITEM | C8 | mean_score=0.6
  3. AF2F9446 | PSI=PSI_14_WOUND_DEHISCENCE | C1 | mean_score=0.0

## Display helpers

In [2]:
def render_rubric_definition(rubric_criteria, max_pos):
    rows = []
    for idx, crit in enumerate(rubric_criteria):
        pts = crit["points"]
        pts_bg = "#28a745" if pts > 0 else "#dc3545"
        row_bg = "#ffffff" if idx % 2 == 0 else "#f8f9fa"
        rows.append(f"""
<tr style="background:{row_bg};">
  <td style="padding:10px; vertical-align:top; white-space:nowrap; font-family:monospace; font-weight:bold;">{crit['id']}</td>
  <td style="padding:6px 10px; vertical-align:middle; text-align:center;">
    <span style="background:{pts_bg}; color:white; padding:4px 10px; border-radius:4px; font-weight:bold;">{pts:+d}</span>
  </td>
  <td style="padding:10px; vertical-align:top;">{crit['question']}</td>
</tr>""")
    return HTML(f"""
<table style="width:100%; border-collapse:collapse; font-family:Helvetica, sans-serif; font-size:13px; border:2px solid #333;">
<thead style="background:#212529; color:#fff;">
<tr>
  <th style="padding:10px; text-align:left;">ID</th>
  <th style="padding:10px; text-align:center;">Points</th>
  <th style="padding:10px; text-align:left;">Criterion question</th>
</tr>
</thead>
<tbody>{"".join(rows)}</tbody>
<tfoot style="background:#ffc107; font-weight:bold;">
<tr><td colspan="3" style="padding:10px;">Max positive = {max_pos}. Score = clip(sum / {max_pos}, 0, 1).</td></tr>
</tfoot>
</table>""")


def render_judge_eval(criteria_rows, mut_model, scope="rubric"):
    rows = []
    last_judge = None
    for cr in criteria_rows:
        if cr["mut_model"] != mut_model or cr["scope"] != scope:
            continue
        answer = str(cr["answer"]).lower()
        ans_bg = "#28a745" if answer == "yes" else "#dc3545"
        pts = cr["criterion_points"]
        pts_bg = "#28a745" if pts > 0 else "#dc3545"
        judge_cell = (f'<td style="padding:8px; font-weight:bold;">{cr["judge"]}</td>'
                      if cr["judge"] != last_judge else
                      '<td style="padding:8px; color:#aaa;">↳</td>')
        last_judge = cr["judge"]
        rows.append(f"""
<tr>
  {judge_cell}
  <td style="padding:8px; font-family:monospace; font-weight:bold;">{cr['criterion_id']}</td>
  <td style="padding:6px; text-align:center;">
    <span style="background:{pts_bg}; color:white; padding:3px 8px; border-radius:3px; font-weight:bold;">{pts:+d}</span>
  </td>
  <td style="padding:8px;">{cr['criterion_question']}</td>
  <td style="padding:6px; text-align:center;">
    <span style="background:{ans_bg}; color:white; padding:5px 10px; border-radius:3px; font-weight:bold;">{answer.upper()}</span>
  </td>
  <td style="padding:8px; color:#333; font-style:italic;">{cr['rationale']}</td>
</tr>""")
    return HTML(f"""
<table style="width:100%; border-collapse:collapse; font-family:Helvetica, sans-serif; font-size:12px; border:2px solid #333;">
<thead style="background:#212529; color:#fff;">
<tr>
  <th style="padding:8px;">Judge</th>
  <th style="padding:8px;">Criterion</th>
  <th style="padding:8px;">Pts</th>
  <th style="padding:8px;">Question</th>
  <th style="padding:8px;">Answer</th>
  <th style="padding:8px;">Rationale</th>
</tr>
</thead>
<tbody>{"".join(rows)}</tbody>
</table>""")

---

# Case 1 — _(populated at runtime from the loaded artifact)_

The case selection rationale is in the artifact JSON. We chose 3 contrasting cases (one easy, one mixed, one hard) to ground the abstract scores.

## Step 1 — Case metadata

In [3]:
case = cases[0]
display(Markdown(f'''
| Field | Value |
|---|---|
| Encounter ID | `{case["encounter_id"]}` |
| PSI code | **{case["psi_code"]}** |
| PSI label | **{case["label"]}** |
| Primary diagnosis | {case.get("primary_dx", "N/A")} ({case.get("primary_dx_desc", "")}) |
| Complexity tier | {case.get("complexity_tier", "?")} |
| LOS bucket | {case.get("los_bucket", "?")} |
| LOS days | {case.get("los_days", "?")} |
| Age / Sex | {case.get("age", "?")}yo {case.get("gender", "?")} |
| Prompt run | **{case["prompt_id"]}** |
'''))

| Field | Value |
|---|---|
| Encounter ID | `FAB54B3F-D06C-4D78-BF25-959CD2BE341F` |
| PSI code | **PSI_15_ACCIDENTAL_PUNCTURE** |
| PSI label | **positive** |
| Primary diagnosis | A41.9 (nan) |
| Complexity tier | hard |
| LOS bucket | long |
| LOS days | 43 |
| Age / Sex | 79yo FEMALE |
| Prompt run | **C8** |

## Step 2 — Prompt + rendered input

In [4]:
display(Markdown("**Prompt text sent to both Models Under Testing:**"))
print(case["prompt_text"])
print()
display(Markdown("**Rendered input (what both models saw):**"))
print(f"Length: {len(case['rendered_input']):,} chars (~{len(case['rendered_input'])//4:,} tokens)")
print()
print(case["rendered_input"])

**Prompt text sent to both Models Under Testing:**

Summarize the lab results below. Identify which values are abnormal and, for each abnormal result, describe what clinical action or follow-up order would be appropriate.

**Rendered input (what both models saw):**

Length: 997,565 chars (~249,391 tokens)

=== Encounter ===
Hospital: 97FD54BC-D85D-4115-95C7-7D91A6CECDBD
Admission: 2018-04-05
Discharge: 2018-05-18
LOS: 43 days
Patient: 79yo FEMALE, UNKNOWN


=== Notes ===

--- PD — 2018-04-05 14:45 ---
  [PD] HPI


Chief Complaint:  VI Complaint


Time Seen by Provider:  14:39


Travel History


International Travel<30 days:  No


Contact w/Intl Traveler<30days:  No


Traveled to known affect area:  No





History of Present Illness




Patient gives a history of a one-day history of crampy abdominal pain,

nonradiating, 8 out of 10, associated with nausea vomiting and diarrhea.

Aggravated by eating or drinking anything.  No alleviating factors.  Patient

denies any associated factors such as fever, rash, back pain, flank pain, chest

pain, headache, sore throat, runny nose or cough.





Primary care is Dr. Messina at Munson Healthcare Grayling Hospital


Allergies to sulfa, Biaxin, penicillin, Coumadin, codeine,


Past medical history significant for cataract, TIA, hypertension, congestive

heart failure, hypercholesterolemia, atrial fibrillation, hypertension,

irritable bowel syndrome, diabetes, hysterectomy, bipolar, claustrophobia





PFSH


Past Medical History


Hx Anticoagulant Therapy:  Yes


Arthritis:  Yes


Atrial Fibrillation:  Yes


Autoimmune Disease:  No


Blood Disorders:  No


Anxiety:  Yes


Depression:  Yes


Heart Rhythm Problems:  Yes (afib)


Cancer:  No


Cardiovascular Problems:  Yes (HTN)


High Cholesterol:  Yes


Chest Pain:  Yes


Congestive Heart Failure:  Yes


Cerebrovascular Accident:  Yes (TIA IN PAST)


Diabetes:  Yes


Diminished Hearing:  No


Endocrine:  No


Gastrointestinal Disorders:  Yes (IBS)


Genitourinary:  No


Headaches:  Yes


Hypertension:  Yes


Immune Disorder:  No


Implanted Vascular Access Dvce:  Yes


Musculoskeletal:  No


Neurologic:  Yes (Neuropathy right leg)


Psychiatric:  Yes


Reproductive:  Yes (Left salping Oophrectomy.)


Respiratory:  No


Immunizations Current:  Yes


Thyroid Disease:  No


Menopausal:  Yes





Past Surgical History


Abdominal Surgery:  Yes (HERNIA SURG 2005, LEFT OVARY SURG 50 YRS AGO)


Eye Surgery:  Yes (CATARACT)


Gynecologic Surgery:  Yes (Left salpingoophrectomy)


Hysterectomy:  Yes


Other Surgery:  Yes (LASER RT EYE)





Social History


Alcohol Use:  No


Tobacco Use:  No


Substance Use:  No





Allergies-Medications


(Allergen,Severity, Reaction):


Coded Allergies:


     Sulfa (Sulfonamide Antibiotics) (Unverified  Allergy, Severe, 8/15/17)


     penicillin G (Unverified  Allergy, Severe, 8/15/17)


     adhesive (Unverified  Allergy, Unknown, 8/15/17)


     codeine (Unverified  Allergy, Unknown, 8/15/17)


     warfarin (Unverified  Allergy, Unknown, 8/15/17)


     clarithromycin (Unverified  Adverse Reaction, Mild, RASH ITCHING, 8/15/17)


Uncoded Allergies:


     TYLENOL 3 (Allergy, Mild, 8/11/08)


Reported Meds & Prescriptions





Reported Meds & Active Scripts


Active


Lisinopril 40 Mg Tab 20 Mg PO DAILY


     take 1/2 tablet or 20mg dpaty


Reported


Coumadin (Warfarin) 5 Mg Tab 7.5 Mg PO FRIDAY


Warfarin 5 Mg Tab 5 Mg PO SUMOTUWETHSA


     Take 1 tablet (5mg) daily on Sunday,Monday,Tuesday,Wednesday,Thursday


     and Saturday


Vitamin D3 (Cholecalciferol) 1,000 Unit Tab 2,000 Units PO DAILY


Saline Nasal Drummond Island (Sodium Chloride) 0.65% Drummond Island 1 Drummond Island EACH NARE BID


Zantac (Ranitidine HCl) 150 Mg Tab 150 Mg PO BID


Pravastatin 10 Mg Tab 10 Mg PO HS


Ferrous Sulfate 325 Mg (65 Mg Iron) Tablet 325 Mg PO TIDPC


Imodium A-D (Loperamide HCl) 2 Mg Capsule 2 Mg PO MI DIRECTED PRN


     One capsule after each loose stool.


     Not to exceed 8 tablets per day.


Lasix (Furosemide) 40 Mg Tab 40 Mg PO DAILY IN THE PM


Lasix (Furosemide) 40 Mg Tab 60 Mg PO DAILY IN THE AM


Folic Acid 1 Mg Tablet 1 Mg PO DAILY


Diltiazem ER 24  Mg Caper 240 Mg PO DAILY


Claritin (Loratadine) 10 Mg Tablet 10 Mg PO DAILY PRN


Benefiber (Wheat Dextrin) 3 Gram/3.8 Gram Powder  PO DAILY


     2 TEASPOONSFUL


Tylenol Extra Strength (Acetaminophen) 500 Mg Tablet 1,000 Mg PO QID PRN


Fish Oil 1000 mg (Elizabethtown-3 Fatty Acids) 300 Mg-1,000 Mg Cap 1,000 Mg PO DAILY


Carvedilol 12.5 Mg Tab 12.5 Mg PO BID


Fluticasone Nasal Drummond Island 50 Mcg/Act Naspr 50 Mcg EACH NARE BID PRN


     50 mcg/spray


Artificial Tears Opth Drops (Polyvinyl Alcohol) 1.4% Soln 1 Drop EACH EYE DAILY

PRN


Potassium Chloride ER (Potassium Chloride) 8 Meq Tab 16 Meq PO DAILY


Clonidine (Clonidine HCl) 0.1 Mg Tab 0.2 Mg PO Q8HR


Metolazone 2.5 Mg Tab 2.5 Mg PO DAILY PRN


Alprazolam 0.5 Mg Tab 0.5 Mg PO BID








Review of Systems


General / Constitutional:  No: Fever


Eyes:  No: Visual changes


HENT:  No: Headaches


Cardiovascular:  No: Chest Pain or Discomfort


Respiratory:  No: Shortness of Breath


Gastrointestinal:  Positive: Nausea, Vomiting, Diarrhea, Abdominal Pain


Genitourinary:  No: Dysuria


Musculoskeletal:  No: Pain


Skin:  No Rash


Neurologic:  No: Weakness


Psychiatric:  No: Depression


Endocrine:  No: Polydipsia


Hematologic/Lymphatic:  No: Easy Bruising





Physical Exam


Narrative


GENERAL:


SKIN: Warm and dry.


HEAD: Atraumatic. Normocephalic.


EYES: Pupils equal and round. No scleral icterus. No injection or drainage.


ENT: No nasal bleeding or discharge.  Mucous membranes pink and moist.


NECK: Trachea midline. No JVD.


CARDIOVASCULAR: Regular rate and rhythm.


RESPIRATORY: No accessory muscle use. Clear to auscultation. Breath sounds

equal bilaterally.


GASTROINTESTINAL: Abdomen soft, diffusely tender to lower quadrant ,

nondistended.


MUSCULOSKELETAL: Extremities without clubbing, cyanosis, or edema. No obvious

deformities.


NEUROLOGICAL: Awake and alert. No obvious cranial nerve deficits.  Motor

grossly within normal limits. Five out of 5 muscle strength in the arms and

legs.  Normal speech.


PSYCHIATRIC: Appropriate mood and affect; insight and judgment normal.





Data




Last Documented VS





Vital Signs








  Date Time  Temp Pulse Resp B/P (MAP) Pulse Ox O2 Delivery O2 Flow Rate FiO2





4/5/18 14:47  69 18





4/5/18 12:25 97.5   103/62 (76) 99








Orders







Complete Blood Count With Diff (4/5/18 12:27)


Basic Metabolic Panel (Bmp) (4/5/18 12:27)


Urinalysis - C+S If Indicated (4/5/18 12:27)


Electrocardiogram (4/5/18 12:39)


Morphine Inj (Morphine Inj) (4/5/18 15:00)


Ondansetron Inj (Zofran Inj) (4/5/18 15:00)


Metronidazole 500 Mg Inj (Flagyl 500 Mg (4/5/18 15:00)


Sodium Chlorid 0.9% 500 Ml Inj (Ns 500 M (4/5/18 15:00)


Levofloxacin 250 Mg Premix Inj (Levaquin (4/5/18 15:00)


Lipase (4/5/18 14:49)


Lactic Acid (4/5/18 14:49)


Ct Abd/Pel W/O Iv Contrast (4/5/18 14:49)


Sodium Chlorid 0.9% 500 Ml Inj (Ns 500 M (4/5/18 17:15)


Prothrombin Time / Inr (Pt) (4/5/18 17:08)


Act Partial Throm Time (Ptt) (4/5/18 17:08)





Labs





Laboratory Tests








Test


  4/5/18


12:49 4/5/18


15:05





White Blood Count 30.7 TH/MM3





Red Blood Count 3.88 MIL/MM3





Hemoglobin 12.8 GM/DL





Hematocrit 37.5 %





Mean Corpuscular Volume 96.5 FL





Mean Corpuscular Hemoglobin 32.9 PG





Mean Corpuscular Hemoglobin


Concent 34.1 %











Red Cell Distribution Width 13.8 %





Platelet Count 152 TH/MM3





Mean Platelet Volume 8.8 FL





Neutrophils (%) (Auto) 95.9 %





Lymphocytes (%) (Auto) 1.7 %





Monocytes (%) (Auto) 2.3 %





Eosinophils (%) (Auto) 0.0 %





Basophils (%) (Auto) 0.1 %





Neutrophils # (Auto) 29.4 TH/MM3





Lymphocytes # (Auto) 0.5 TH/MM3





Monocytes # (Auto) 0.7 TH/MM3





Eosinophils # (Auto) 0.0 TH/MM3





Basophils # (Auto) 0.0 TH/MM3





CBC Comment AUTO DIFF





Differential Total Cells


Counted 100











Neutrophils % (Manual) 89 %





Band Neutrophils % 7 %





Lymphocytes % 1 %





Monocytes % 1 %





Neutrophils # (Manual) 30.1 TH/MM3





Metamyelocytes 2 %





Differential Comment


  FINAL DIFF


MANUAL








Toxic Vacuolation PRESENT





Platelet Estimate NORMAL





Platelet Morphology Comment NORMAL





Blood Urea Nitrogen 61 MG/DL





Creatinine 2.47 MG/DL





Random Glucose 116 MG/DL





Calcium Level 8.7 MG/DL





Sodium Level 118 MEQ/L





Potassium Level 3.2 MEQ/L





Chloride Level 81 MEQ/L





Carbon Dioxide Level 24.4 MEQ/L





Anion Gap 13 MEQ/L





Estimat Glomerular Filtration


Rate 23 ML/MIN











Lipase 47 U/L





Lactic Acid Level  1.5 mmol/L











Wyandot Memorial Hospital


Medical Decision Making


Medical Screen Exam Complete:  Yes


Emergency Medical Condition:  Yes


Medical Record Reviewed:  Yes


Interpretation(s)


EKG shows atrial fibrillation with controlled ventricular rate, PVCs, no STEMI

pattern noted.


Differential Diagnosis


Appendicitis versus colitis versus diverticulitis versus small bowel

obstruction versus bacterial enteritis versus viral enteritis


Narrative Course


CBC shows a leukocytosis of 30,000, with left shift of 96%, 7% bandemia, no

anemia, normal platelet count.


Basic metabolic profile shows hyponatremia 118, hypokalemia 3.2, hypochloremia

of 81, no anion gap normal bicarb, BUN and creatinine abnormal at 61/2.47, with

an estimated GFR of 23.


Due to patient's CHF history patient will be given IV fluids but a careful

bolus dose of 500 cc at a time with frequent reevaluation in order to avoid

pulmonary edema, renal dose of Levaquin will be used, Flagyl as well IV to

address any intra-abdominal source of infection.  Based on the leukocytosis,

this meets sepsis criteria





CT read by radiologist as there is free intraperitoneal air, inflammatory

changes in the low pelvis involving both a portion of the sigmoid colon and

small bowel.  7 x 5.6 cm low-attenuation area within the uterus probably

resending fluid within the uterine cavity this could also represent a

degenerating fibroid.  Cardiomegaly noted


Critical Care Narrative


CRITICAL CARE NOTE: With evaluation of the patient, labs, EKG, receipt of

radiologic studies, administration of medications, reevaluation the patient and

discussion of the patient with the admitting physicians, the total critical

care time was [60] minutes. Time to perform other separately billable

procedures was not included in the critical care time.





Sepsis Criteria


SIRS Criteria (2 or more):  WBC > 79061, < 4000 or > 10% bands


Sepsis Criteria (SIRS+source):  Infect source susp/known


Criteria Outcome:  Meets sepsis criteria





Diagnosis





 Primary Impression:


 Acute renal insufficiency


 Additional Impressions:


 Hyponatremia


 Free intraperitoneal air


 Likely diverticular abscess with perforation





Admitting Information


Admitting Physician Requests:  Admit











Juni Grier MD Apr 5, 2018 14:45

--- RADRPT — 2018-04-05 16:21 ---
  [RADRPT] EXAM DATE/TIME:  04/05/2018 15:42



HALIFAX COMPARISON:     CT THORAX W/O CONTRAST, January 05, 2017, 12:51.



INDICATIONS :     Patient compalains of abdominal pain. bladder distention.



ORAL CONTRAST:      No oral contrast ingested.



RADIATION DOSE:     8.5 CTDIvol (mGy)



MEDICAL HISTORY :     Hypertension. Irritable bowel syndrome.

SURGICAL HISTORY :      Hysterectomy. left oophorectomy

ENCOUNTER:      Initial

ACUITY:      2 days

PAIN SCALE:      5/10

LOCATION:        lower quadrant abdomen



TECHNIQUE:     Volumetric scanning of the abdomen and pelvis was performed.  Using automated exposure
 control and adjustment of the mA and/or kV according to patient size, radiation dose was kept as low
 as reasonably achievable to obtain optimal diagnostic quality images.  DICOM format image data is av
ailable electronically for review and comparison.



FINDINGS:

Imaging through the lung bases demonstrates advanced cardiomegaly.



Examination of the upper abdomen demonstrate punctate collections of free intraperitoneal air.



The appearance of the liver, spleen, pancreas, adrenal glands and kidneys is within normal limits. Th
e abdominal aorta is normal in caliber. There is no significant retroperitoneal adenopathy.



The visualized loops of small and large bowel in the upper abdomen are unremarkable.



There is no free fluid within the pelvis. There numerous diverticuli evident throughout the distal si
gmoid colon. There are inflammatory changes seen involving the distal sigmoid colon and possibly the
small bowel in the low pelvis.



The visualized bony structures demonstrate a rotatory scoliosis and degenerative changes but are othe
rwise intact. No free fluid is seen within the pelvis. No iliac or inguinal adenopathy is seen.



The examination does demonstrate a 7.0 x 5.6 cm area of decreased attenuation within the central aspe
ct of the uterus. This could suggest uterine obstruction. Ultrasound for further assessment would be
of benefit.



CONCLUSION:

1. There is free intraperitoneal air. There are inflammatory changes in the low pelvis involving both
 a portion of sigmoid colon and the small bowel. Surgical consult is warranted.

2. 7.0 x 5.6 cm low attenuation area within the uterus probably representing fluid within the uterine
 cavity. This could also represent degenerating fibroid. Ultrasound may be of benefit for further ass
essment. This is indeterminate appearance by noncontrast CT imaging. Ultrasound could be performed fo
r further assessment.

3. 2.5 cm well-circumscribed exophytic lesion projecting off the lower pole of the right kidney. This
 measures only 3 Hounsfield units and is felt to represent a simple cyst.

4. Advanced cardiomegaly.

5. Results were called to the ED.





 Edmundo Goodrich MD on April 05, 2018 at 16:05

Board Certified Radiologist.

 This report was verified electronically.

--- PD.CONS — 2018-04-05 18:10 ---
  [PD.CONS] General Surgery Consult


Asked to see this 79 Y/O lady with 24-36 hours of abdominal pain; pain started

in lower midline sometime yesterday and progressively worsened through the

night and this AM. Has more pain on the left side than the right and when she

moves, it's still in the middle. Has not passed flatus today but had a soft BM

earlier today. No nausea or emesis. No previous h/o such pain.





She also states she has had several episodes of thick, yellow, foul-smelling

vaginal discharge over the last two days.





PMH:





Multiple medical diseases including HTN, cardiomegaly, ? PHT, COPD, A-fib, Type

3 CKD, significant ASCVD.





Meds: see chart





EXAM:





HEENT: ok





NECK: supple, no thyromegaly





CHEST: BS clear





HEART: irregular rhythm, muffled sounds





LUNGS: clear





ABDOMEN: soft; distended mainly in lower abdomen; is quite tender in midline

and LLQ with localized percussive rebound and voluntary guarding; RLQ and upper

abdomen benign.





EXT: No edema








 Laboratory Tests








Test


  4/5/18


12:49 4/5/18


15:05





White Blood Count 30.7 TH/MM3





Red Blood Count 3.88 MIL/MM3





Hemoglobin 12.8 GM/DL





Hematocrit 37.5 %





Mean Corpuscular Volume 96.5 FL





Mean Corpuscular Hemoglobin 32.9 PG





Mean Corpuscular Hemoglobin


Concent 34.1 %











Red Cell Distribution Width 13.8 %





Platelet Count 152 TH/MM3





Mean Platelet Volume 8.8 FL





Neutrophils (%) (Auto) 95.9 %





Lymphocytes (%) (Auto) 1.7 %





Monocytes (%) (Auto) 2.3 %





Eosinophils (%) (Auto) 0.0 %





Basophils (%) (Auto) 0.1 %





Neutrophils # (Auto) 29.4 TH/MM3





Lymphocytes # (Auto) 0.5 TH/MM3





Monocytes # (Auto) 0.7 TH/MM3





Eosinophils # (Auto) 0.0 TH/MM3





Basophils # (Auto) 0.0 TH/MM3





CBC Comment AUTO DIFF





Differential Total Cells


Counted 100











Neutrophils % (Manual) 89 %





Band Neutrophils % 7 %





Lymphocytes % 1 %





Monocytes % 1 %





Neutrophils # (Manual) 30.1 TH/MM3





Metamyelocytes 2 %





Differential Comment


  FINAL DIFF


MANUAL








Toxic Vacuolation PRESENT





Platelet Estimate NORMAL





Platelet Morphology Comment NORMAL





Blood Urea Nitrogen 61 MG/DL





Creatinine 2.47 MG/DL





Random Glucose 116 MG/DL





Calcium Level 8.7 MG/DL





Sodium Level 118 MEQ/L





Potassium Level 3.2 MEQ/L





Chloride Level 81 MEQ/L





Carbon Dioxide Level 24.4 MEQ/L





Anion Gap 13 MEQ/L





Estimat Glomerular Filtration


Rate 23 ML/MIN











Lipase 47 U/L





Lactic Acid Level  1.5 mmol/L











Last 72 hours Impressions








Abdomen/Pelvis CT 4/5/18 5644 Sigjason





Impressions:





 Service Date/Time:  Thursday, April 5, 2018 15:42 - CONCLUSION:  1. There is





 free intraperitoneal air. There are inflammatory changes in the low pelvis





 involving both a portion of sigmoid colon and the small bowel. Surgical

consult





 is warranted. 2. 7.0 x 5.6 cm low attenuation area within the uterus probably





 representing fluid within the uterine cavity. This could also represent





 degenerating fibroid. Ultrasound may be of benefit for further assessment.

This





 is indeterminate appearance by noncontrast CT imaging. Ultrasound could be





 performed for further assessment. 3. 2.5 cm well-circumscribed exophytic

lesion





 projecting off the lower pole of the right kidney. This measures only 3





 Hounsfield units and is felt to represent a simple cyst. 4. Advanced





 cardiomegaly.  5. Results were called to the ED.     New Harper MD





IMPRESSION:





Small amount of free air; extensive diverticulosis with inflammatory changes in

the LLQ (? diverticulitis?). She has a large, tender uterus, which on viewing

CT appears to be fluid. In conjunction with thick, yellow, foul smelling

vaginal discharge, and in view of 30K WBC (which is unusual for diverticulitis)

, I am concerned about a septic process in the uterus.





PLAN: I have spoken with Dr. Pacheco who is admitting her to Kindred Hospital. She has already

received Levaquin and Flagyl, and Dr. Pacheco is ordering Rocephin in addition.

She is receiving fluid resuscitation and electrolyte replacement. We have also

agreed to d/c the Coumadin she has been on and not immediately reverse it.





She will be observed in the Kindred Hospital and I have placed a consult to Dr. Eloy Trinh

for evaluation of the fluid in the uterus.











Apolinar Franco MD Apr 5, 2018 18:09

--- RADRPT — 2018-04-05 19:27 ---
  [RADRPT] EXAM DATE/TIME:  04/05/2018 19:03



HALIFAX COMPARISON:

No previous studies available for comparison.





INDICATIONS :

Shortness of breath.





MEDICAL HISTORY :

Hypertension. Irritable bowel syndrome. Diverticulitis.



SURGICAL HISTORY :

Hysterectomy. left oophorectomy



ENCOUNTER:

Initial



ACUITY:

1 day



PAIN SCORE:

0/10



LOCATION:

Bilateral chest



FINDINGS:

A single view of the chest demonstrates cardiomegaly with minimal interstitial edema pattern. Elevate
d right hemidiaphragm. No significant effusion.



CONCLUSION:     Cardiomegaly with minimal interstitial edema pattern.





 Prasanth Cantor MD on April 05, 2018 at 19:24

Board Certified Radiologist.

 This report was verified electronically.

--- EKG — 2018-04-05 20:27 ---
  [EKG] Date Performed: 04/05/2018       Time Performed: 12:39:23



PTAGE:      78 years



EKG:      ATRIAL FIBRILLATION WITH ABERRANT CONDUCTION OR VENTRICULAR PREMATURE COMPLEXES ANTEROSEPTA
L MYOCARDIAL INFARCTION ABNORMAL ECG



PREVIOUS TRACING       : 05/15/2017 23.08 No significant change from previous tracing noted.



DOCTOR:   Zac Koenig  Interpretating Date/Time  04/05/2018 20:26:09

--- RADRPT — 2018-04-05 22:35 ---
  [RADRPT] EXAM DATE/TIME:  04/05/2018 21:32



HALIFAX COMPARISON:

No previous studies available for comparison.







INDICATIONS :

Follow up CT.





MEDICAL HISTORY :

Hypertension



SURGICAL HISTORY :

left oophorectomy



ENCOUNTER:

Initial



ACUITY:

3 days



PAIN SCORE:

5



LOCATION:

Lower quadrant abdomen



MEASUREMENTS:



UTERUS:

8.2 x 6.5 x 5.4 cm



ENDOMETRIAL STRIPE:

>20 mm



RIGHT OVARY:

2.2 x 1.0 x 1.5  cm



LEFT OVARY:

cm Surgically absent



FINDINGS:


## Step 3 — Ground truth

In [5]:
display(Markdown("**Ground truth (not shown to either model):**"))
print(case["ground_truth"])

**Ground truth (not shown to either model):**

## Step 4 — Opus 4.7 response

In [6]:
display(Markdown("**Opus 4.7 response:**"))
print(case["opus_response"])
display(Markdown(f"**Opus scores:** Sonnet={case['opus_score_sonnet']}, GPT-mini={case['opus_score_gpt_mini']}, Gemini={case['opus_score_gemini']}, mean={case['opus_score_mean']}"))

**Opus 4.7 response:**

# Lab Results Summary

## Key Abnormal Values & Recommended Actions

### Hematologic/Infectious
- **WBC markedly elevated** (peak 40.8, admission 30.7 TH/MM3) with **bandemia (up to 27%)**, toxic granulation, Döhle bodies → **Severe sepsis from perforated diverticulitis/pyometra/intra-abdominal abscess.** Action taken: broad-spectrum IV antibiotics (aztreonam, Flagyl, vancomycin, meropenem, micafu

**Opus scores:** Sonnet=1.0, GPT-mini=0.42, Gemini=1.0, mean=0.81

### Per-judge evaluation of Opus 4.7's response

In [7]:
display(render_judge_eval(case["criteria"], "claude-opus-4-7", scope="rubric"))

### Universal criteria (Opus)

In [8]:
display(render_judge_eval(case["criteria"], "claude-opus-4-7", scope="universal"))

## Step 5 — GPT-5.5 response

In [9]:
display(Markdown("**GPT-5.5 response:**"))
print(case["gpt55_response"])
display(Markdown(f"**GPT-5.5 scores:** Sonnet={case['gpt55_score_sonnet']}, GPT-mini={case['gpt55_score_gpt_mini']}, Gemini={case['gpt55_score_gemini']}, mean={case['gpt55_score_mean']}"))

**GPT-5.5 response:**

nan

**GPT-5.5 scores:** Sonnet=0.0, GPT-mini=0.0, Gemini=0.0, mean=0.0

### Per-judge evaluation of GPT-5.5's response

In [10]:
display(render_judge_eval(case["criteria"], "gpt-5.5", scope="rubric"))

### Universal criteria (GPT-5.5)

In [11]:
display(render_judge_eval(case["criteria"], "gpt-5.5", scope="universal"))

## Step 6 — Rubric definition (what the judges graded against)

In [12]:
display(render_rubric_definition(case["rubric_criteria"], case["rubric_max_positive"]))

## Step 7 — Comparative scoring summary

In [13]:
summary = pd.DataFrame({
    "Opus 4.7": [case["opus_score_sonnet"], case["opus_score_gpt_mini"], case["opus_score_gemini"], case["opus_score_mean"]],
    "GPT-5.5":  [case["gpt55_score_sonnet"], case["gpt55_score_gpt_mini"], case["gpt55_score_gemini"], case["gpt55_score_mean"]],
}, index=["Sonnet judge", "GPT-mini judge", "Gemini judge", "Mean"]).round(2)
display(Markdown("**Scores per (Model Under Testing × judge) and overall mean:**"))
display(summary)

**Scores per (Model Under Testing × judge) and overall mean:**

                Opus 4.7  GPT-5.5
Sonnet judge        1.00      0.0
GPT-mini judge      0.42      0.0
Gemini judge        1.00      0.0
Mean                0.81      0.0

---

# Case 2 — _(populated at runtime from the loaded artifact)_

The case selection rationale is in the artifact JSON. We chose 3 contrasting cases (one easy, one mixed, one hard) to ground the abstract scores.

## Step 1 — Case metadata

In [14]:
case = cases[1]
display(Markdown(f'''
| Field | Value |
|---|---|
| Encounter ID | `{case["encounter_id"]}` |
| PSI code | **{case["psi_code"]}** |
| PSI label | **{case["label"]}** |
| Primary diagnosis | {case.get("primary_dx", "N/A")} ({case.get("primary_dx_desc", "")}) |
| Complexity tier | {case.get("complexity_tier", "?")} |
| LOS bucket | {case.get("los_bucket", "?")} |
| LOS days | {case.get("los_days", "?")} |
| Age / Sex | {case.get("age", "?")}yo {case.get("gender", "?")} |
| Prompt run | **{case["prompt_id"]}** |
'''))

| Field | Value |
|---|---|
| Encounter ID | `3F10EE61-97DC-4A05-9521-DC886890584E` |
| PSI code | **PSI_05_RETAINED_ITEM** |
| PSI label | **positive** |
| Primary diagnosis | T84.028A (nan) |
| Complexity tier | hard |
| LOS bucket | long |
| LOS days | 64 |
| Age / Sex | 78yo FEMALE |
| Prompt run | **C8** |

## Step 2 — Prompt + rendered input

In [15]:
display(Markdown("**Prompt text sent to both Models Under Testing:**"))
print(case["prompt_text"])
print()
display(Markdown("**Rendered input (what both models saw):**"))
print(f"Length: {len(case['rendered_input']):,} chars (~{len(case['rendered_input'])//4:,} tokens)")
print()
print(case["rendered_input"])

**Prompt text sent to both Models Under Testing:**

Summarize the lab results below. Identify which values are abnormal and, for each abnormal result, describe what clinical action or follow-up order would be appropriate.

**Rendered input (what both models saw):**

Length: 990,177 chars (~247,544 tokens)

=== Encounter ===
Hospital: 2946041F-ADA8-43D9-B7D9-20DCB22F4EAC
Admission: 2020-07-06
Discharge: 2020-09-08
LOS: 64 days
Patient: 78yo FEMALE, UNKNOWN


=== Notes ===

--- PN — 2020-07-06 14:05 ---
  [PN] Progress Note (short form)





- Note


Progress Note:





77F s/p removal of hardware L3-L5 (including L4-L5 intervertebral cage),

inspection of fusion mass, L3-S1 laminectomies, L5-S1 PLIF, L3-S1 posterior

instrumented spinal fusion POD #0.


Incidental durotomy during cage removal successfully repaired; Multiple valsalva

maneuvers negative for CSF leak.





-Admit to ICU post-op.


-Pain control: NO NSAID's; patient received intra-op paraspinal muscle block

w/Exparel & marcaine; OK to use ultrasonic cleaner if needed; transition to oral analgesia

post-op.


-DVT PPx:


   -Mechanical only: SHAISTA's, SCD's.


   -Chemical: None.


-Incentive spirometry q15 min.


-NPO until flatus.


-Saxena care; d/c when ambulating.


-Ancef post-op x 3 doses.


-PT/OT/Rehab, OOB.


-WBAT B/L LE.


-No bending, lifting (>5 lbs), or twisting for 9-12 months.


-Care per ICU & medical hospitalist teams.


-Discharge planning: Girma villanueva; f/u 7-10 days after rehab discharge at

Lehigh Valley Hospital - Muhlenberg OrthopaedicLiberty Hospital office; call for appointment; (399) 109-5176.


-Will follow.





Pierre Martinez MD (Orthopaedic Surgery).

--- OP — 2020-07-06 14:09 ---
  [OP] Operative Note





- Note:


Operative Date: 07/06/20


Pre-Operative Diagnosis: Migrated intervertebral cage.  Radiculopathy.  Back

pain


Operation: 1. Removal of hardware.  2. Inspections of fusion mass.  3. L3-S1

laminectomies.  4. L5-S1 PLIF.  5. L3-S1 PISF


Post-Operative Diagnosis: Same as Pre-op


Surgeon: Sridhar Vigil


pie dough roller: Ronald Vigil


Anesthesiologist/manager intensive care: Tesha Carter


Anesthesia: General


Specimens Removed: Hardware


Estimated Blood Loss (mls): 375


Blood Volume Replaced (mls): 125 (Cell Saver)


Fluid Volume Replaced (mls): 1,700 (Crystalloid)


Operative Report Dictated: Yes

--- OP — 2020-07-06 14:58 ---
  [OP] DATE OF OPERATION:



DATE OF DICTATION:  07/06/2020



ADDENDUMClosure:  Fascial 1 Vicryl, subcutaneous 1 and 2-0 Vicryl, skin guadalupe.  No

drain was utilized.  One g vancomycin given just at the time of closure.  Operation

went well.  No complications.  Blood loss 375 mL, 125 mL given back via cell saver.





MD TANYA Dennis/1784676

DD: 07/06/2020 14:30

DT: 07/06/2020 14:55

Job #:  14754

--- CONSULT — 2020-07-06 19:51 ---
  [CONSULT] Consultation:


REQUESTING PROVIDER: Dr. Jimenez





CONSULT REQUEST: We have been asked to medically evaluate this patient for

postoperative management





HISTORY OF PRESENT ILLNESS:


Patient is a 78 year old female with history of hypertension, dementia,

depression, spinal stenosis, neuropathy admitted for removal of L3-L5 hardware,

including L4-L5 intervertebral cage, L3-S1 laminectomy, L5-S1 PLIF, L3-S1

posterior instrumented spinal fusion.


Upon my encounter, patient endorses mild pain (5/10). Denies subjective fevers,

chills, shortness of breath, chest pain, palpitations, abdominal pain, nausea,

vomiting. diarrhea.


Additional history obtained from patient's niece; endorses history of prior back

surgery 8 years ago (?Dr Goodwin)- removed today due to worsening pain, and

reported spinal impingement. At baseline, patient does not ambulate, and has 24

hour home care.





REVIEW OF SYSTEMS:


As per HPI. At baseline, patient has history of dementia and is unable to

provide further historical details.





PHYSICAL EXAMINATION





                               Vital Signs - 24 hr











  07/06/20 07/06/20 07/06/20





  06:38 06:40 14:26





Temperature 97.1 F L  98.3 F





Pulse Rate 63  94 H





Respiratory 16  10





Rate





Blood Pressure 175/82 H  185/90 H





O2 Sat by Pulse  97 100





Oximetry (%)



















  14:45 15:00 15:15





Temperature





Pulse Rate 72 77 76





Respiratory 10 9 L 13










Blood Pressure 164/75 157/75 153/72





O2 Sat by Pulse 100 100 100
























  15:30 15:45 16:00





Lemuel Shattuck Hospitalature





Pulse Rate 88 87 82





Respiratory 10 10 14










Blood Pressure 148/83 163/82 153/79





























  16:15 16:30 16:45










Pulse Rate 81 86 86





Respiratory 13 12 15










Blood Pressure 156/91 158/79 159/80





O2 Sat by Pulse 100 99 98
























  17:00 17:15 17:30










Pulse Rate 82 76 81





Respiratory 11 10 12










Blood Pressure 155/80 178/86 H 182/76 H





O2 Sat by Pulse 99 99 100
























  17:46 18:29 18:31





Temperature 97.7 F 98.0 F





Pulse Rate 82 64





Respiratory 12 13 13










Blood Pressure 198/83 H 179/83 H





O2 Sat by Pulse 100  100
















GENERAL: Awake, alert, and oriented to person, and place in no acute distress.


HEAD: Normal with no signs of trauma.


EYES: Pupils equal, round and reactive to light, extraocular movements intact,

conjunctiva clear.


EARS, NOSE, THROAT: oropharynx clear without exudates. Moist mucous membranes.


NECK: Normal range of motion, supple without lymphadenopathy, JVD, or masses.


LUNGS: Breath sounds equal, clear to auscultation bilaterally. No wheezes, and

no crackles. No accessory muscle use.


HEART: Regular rate and rhythm, normal S1 and S2. Holosystolic murmur

auscultated.


ABDOMEN: Soft, nontender, not distended, normoactive bowel sounds, no guarding,

no rebound, no masses.


MUSCULOSKELETAL: Normal range of motion at all joints. No bony deformities or

tenderness. No CVA tenderness.


EXTREMITIES: 2+ radial, dorsalis pedis pulses, warm, well-perfused. No cyanosis.

No peripheral edema.


NEUROLOGICAL:  Cranial nerves II-XII intact. Normal speech


PSYCHIATRIC: Cooperative. Good eye contact. Appropriate mood and affect.


SKIN: Warm, dry. Lumbar surgical site bandaged clean, dry.








                         Laboratory Results - last 24 hr











  07/06/20 07/06/20





  06:08 08:30





Blood Type  O POSITIVE  O POSITIVE





Antibody Screen  Negative








Active Medications











Generic Name Dose Route Start Last Admin





  Trade Name Freq  PRN Reason Stop Dose Admin





Acetaminophen  1,000 mg  07/06/20 13:57





  Ofirmev Injection -  IVPB  07/07/20 13:56





  PRN PRN





  If narcotics are ineffective





Citalopram Hydrobromide  20 mg  07/06/20 22:00





  Celexa -  PO





  HS MARQUES





Diazepam  2 mg  07/06/20 13:57





  Valium -  PO





  Q8H PRN





  MUSCLE SPASMS





Lactated Ringer's  1,000 mls @ 125 mls/hr  07/06/20 14:00





  Lactated Ringers Solution  IV





  ASDIR MARQUES





Cefazolin Sodium 1 gm/  50 mls @ 100 mls/hr  07/06/20 20:00





  Dextrose  IVPB  07/07/20 03:29





  Q6H-IV MARQUES





Losartan Potassium  25 mg  07/07/20 10:00





  Cozaar -  PO





  DAILY MARQUES





Mirtazapine  7.5 mg  07/06/20 22:00





  Remeron -  PO










Ondansetron HCl  4 mg  07/06/20 13:57





  Zofran Injection  IVPUSH





  Q6H PRN





  NAUSEA AND/OR VOMITING





Oxycodone HCl  10 mg  07/06/20 13:57





  Roxicodone -  PO





  Q4H PRN





  PAIN LEVEL 6-10





Oxycodone HCl  5 mg  07/06/20 13:57















  PAIN LEVEL 1-5











ASSESSMENT/PLAN:


Patient is a 78 year old female with history of dementia, hypertension, spinal

stenosis s/p removal of L3-L5 hardware, including L4-L5 intervertebral cage, L3-

S1 laminectomy, L5-S1 PLIF, L3-S1 posterior instrumented spinal fusion.





Neurologic


History of dementia, depression


 -Continue home Mirtazapine, Citalopram


 -Monitor for signs of mental status changes





Pulmonary


 -Currently saturating well, without respiratory distress.


 -Incentive spirometer q15 minutes


 -Monitor for change in oxygen requirements, respiratory distress





Cardiovascular


History of hypertension


 -Losartan 25mg PO daily


 -Labetalol 10mg IV push for systolic BP greater than 160mmHg





Musculoskeletal


S/P removal of L3-L5 hardware, including L4-L5 intervertebral cage, L3-S1

laminectomy, L5-S1 PLIF, L3-S1 posterior instrumented spinal fusion.


 -Pain control with Oxycodone, Morphine. NO NSAIDs per orthopedic surgery


 -Physical therapy consult





Gastrointestinal


 -NPO until patient is passing flatus


 -Gentle hydration with IV normal saline at 50mL/ hour





FEN


 -IV normal saline at 50mL/ hour


 -Follow BMP


 -NPO until flatus





Prophylaxis


 -SCDs bilateral lower extremities





Disposition:


We will continue to follow the patient. Thank you for this consultative

opportunity.











Visit type





- Emergency Visit


Emergency Visit: Yes


ED Registration Date: 07/06/20


Care time: The patient presented to the Emergency Department on the above date

and was hospitalized for further evaluation of their emergent condition.





- New Patient


This patient is new to me today: Yes


Date on this admission: 07/06/20





- Critical Care


Critical Care patient: Yes


Total Critical Care Time (in minutes): 37


Critical Care Statement: The care of this patient involved high complexity

decision making to prevent further life threatening deterioration of the

patient's condition and/or to evaluate & treat vital organ system(s) failure or

risk of failure.





ATTENDING PHYSICIAN STATEMENT





I saw and evaluated the patient.


I reviewed the resident's note and discussed the case with the resident.


I agree with the resident's findings and plan as documented.








SUBJECTIVE:








OBJECTIVE:








ASSESSMENT AND PLAN:

--- PN — 2020-07-07 13:59 ---
  [PN] <Eros Morris MD - Last Filed: 07/08/20 12:19>


Physical Exam:


SUBJECTIVE: Patient seen and examined








OBJECTIVE:





                                   Vital Signs











 Period  Temp  Pulse  Resp  BP Sys/Rios  Pulse Ox





 Last 24 Hr  98.2 F-98.7 F  76-87  15-25  130-150/54-68  100











GENERAL: The patient is awake, alert, and fully oriented, in no acute distress.


HEAD: Normal with no signs of trauma.


EYES: PERRL, extraocular movements intact, sclera anicteric, conjunctiva clear.

No ptosis.


ENT: Ears normal, nares patent, oropharynx clear without exudates, moist mucous


membranes.


NECK: Trachea midline, full range of motion, supple.


LUNGS: Breath sounds equal, clear to auscultation bilaterally, no wheezes, no

crackles, no


accessory muscle use.


HEART: Regular rate and rhythm, S1, S2 without murmur, rub or gallop.


ABDOMEN: Soft, nontender, nondistended, normoactive bowel sounds, no guarding,

no


rebound, no hepatosplenomegaly, no masses.


EXTREMITIES: 2+ pulses, warm, well-perfused, no edema.


NEUROLOGICAL: Cranial nerves II through XII grossly intact. Normal speech, gait

not


observed.


PSYCH: Normal mood, normal affect.


SKIN: Warm, dry, normal turgor, no rashes or lesions noted














                         Laboratory Results - last 24 hr











  07/08/20 07/08/20





  05:45 05:45





WBC  19.9 H





RBC  3.45 L





Hgb  9.2 L





Hct  29.0 L D





MCV  84.2





MCH  26.6





MCHC  31.6 L





RDW  13.3





Plt Count  265





MPV  8.1





Absolute Neuts (auto)  17.3 H





Neutrophils %  86.7 H





Lymphocytes %  7.1 L





Monocytes %  5.7





Eosinophils %  0.1





Basophils %  0.4





Nucleated RBC %  0





Sodium   137





Potassium   4.2





Chloride   103





Carbon Dioxide   29





Anion Gap   5 L





BUN   8.6





Creatinine   0.6





Est GFR (CKD-EPI)AfAm   101.90





Est GFR (CKD-EPI)NonAf   87.92





Random Glucose   89





Calcium   8.8





Phosphorus   2.1 L





Magnesium   1.8





Total Bilirubin   0.7





AST   20





ALT   11 L





Alkaline Phosphatase   71





Total Protein   5.6 L





Albumin   2.1 L








Active Medications











Generic Name Dose Route Start Last Admin





  Trade Name David  PRN Reason Stop Dose Admin





Citalopram Hydrobromide  20 mg  07/06/20 22:00  07/07/20 21:44





  Celexa -  PO   20 mg





  HS VICTOR M   Administration





Diazepam  2 mg  07/06/20 13:57





  Valium -  PO





  Q8H PRN





  MUSCLE SPASMS





Lactated Ringer's  1,000 mls @ 125 mls/hr  07/06/20 14:00  07/08/20 06:21





  Lactated Ringers Solution  IV   125 mls/hr





  ASDIR VICTOR M   Administration





Losartan Potassium  25 mg  07/07/20 10:00  07/08/20 10:43





  Cozaar -  PO   25 mg





  DAILY VICTOR M   Administration





Mirtazapine  7.5 mg  07/06/20 22:00  07/07/20 21:45





  Remeron -  PO   7.5 mg










Ondansetron HCl  4 mg  07/06/20 13:57





  Zofran Injection  IVPUSH





  Q6H PRN





  NAUSEA AND/OR VOMITING





Oxycodone HCl  10 mg  07/06/20 13:57  07/07/20 01:59





  Roxicodone -  PO   10 mg





  Q4H PRN   Administration





  PAIN LEVEL 6-10





Oxycodone HCl  5 mg  07/06/20 13:57  07/08/20 06:21





  Roxicodone -  PO   5 mg










  PAIN LEVEL 1-5











ASSESSMENT/PLAN:


Lumbar Spinal Stenosis


s/p Removal of L3-L5 hardware, including L4-L5 intervertebral cage, L3-S1

laminectomy, L5-S1 PLIF, L3-S1 posterior instrumented spinal fusion


HTN





-  pain control


-  incentive spirometry


-  rehab/PT


-  DVT prophylaxis


-  disposition per surgery





ATTENDING PHYSICIAN STATEMENT





I saw and evaluated the patient.


I reviewed the resident's note and discussed the case with the resident.


I agree with the resident's findings and plan as documented.








SUBJECTIVE:
















ASSESSMENT AND PLAN:








<AnthonyTami - Last Filed: 07/09/20 16:49>




SUBJECTIVE: Patient seen and examined. Stated that her pain is 5/10. She is POD

#1 of removal of L3-L5 hardware, including L4-L5 intervertebral cage, L3-S1

laminectomy, L5-S1 PLIF, L3-S1 posterior instrumented spinal fusion.





























 Last 24 Hr  97.7 F-98.3 F  58-94  9-17  133-198/57-91











GENERAL: The patient is awake, alert and in no acute distress.


HEENT: NCAT


LUNGS: Breath sounds equal, clear to auscultation bilaterally, no wheezes


HEART: Regular rate and rhythm, S1, S2 without murmur


ABDOMEN: Soft, nondistended


EXTREMITIES: warm, well-perfused, no edema. Spontaneous movement in all 4

extremities.


SKIN: Warm, dry. Surgical site on back is clean, dry and intact.











                             Laboratory Last Values











WBC  23.4 K/mm3 (4.0-10.0)  H  07/07/20  05:40





RBC  4.41 M/mm3 (3.60-5.2)   07/07/20  05:40





Hgb  11.8 GM/dL (10.7-15.3)   07/07/20  05:40





Hct  37.7 % (32.4-45.2)   07/07/20  05:40





MCV  85.5 fl (80-96)   07/07/20  05:40





MCH  26.7 pg (25.7-33.7)   07/07/20  05:40





MCHC  31.3 g/dl (32.0-36.0)  L  07/07/20  05:40





RDW  13.4 % (11.6-15.6)   07/07/20  05:40





Plt Count  293 K/MM3 (134-434)   07/07/20  05:40





MPV  8.7 fl (7.5-11.1)   07/07/20  05:40





Sodium  138 mmol/L (136-145)   07/07/20  05:40





Potassium  4.2 mmol/L (3.5-5.1)   07/07/20  05:40





Chloride  104 mmol/L ()   07/07/20  05:40





Carbon Dioxide  24 mmol/L (21-32)   07/07/20  05:40





Anion Gap  11 MMOL/L (8-16)   07/07/20  05:40





BUN  14.4 mg/dL (7-18)   07/07/20  05:40





Creatinine  0.9 mg/dL (0.55-1.3)   07/07/20  05:40





Est GFR (CKD-EPI)AfAm  71.48   07/07/20  05:40





Est GFR (CKD-EPI)NonAf  61.67   07/07/20  05:40





Random Glucose  99 mg/dL ()   07/07/20  05:40





Calcium  9.9 mg/dL (8.5-10.1)   07/07/20  05:40





Phosphorus  3.6 mg/dL (2.5-4.9)   07/07/20  05:40





Magnesium  1.5 mg/dL (1.8-2.4)  L  07/07/20  05:40





Blood Type  O POSITIVE   07/06/20  08:30





Antibody Screen  Negative   07/06/20  06:08

























Acetaminophen (Ofirmev Injection -)  1,000 mg IVPB PRN PRN


   PRN Reason: If narcotics are ineffective


   Stop: 07/07/20 13:56


   Last Admin: 07/06/20 21:57 Dose:  1,000 mg


   Documented by:


Citalopram Hydrobromide (Celexa -)  20 mg PO HS Atrium Health Harrisburg


   Last Admin: 07/06/20 21:59 Dose:  20 mg




Diazepam (Valium -)  2 mg PO Q8H PRN


   PRN Reason: MUSCLE SPASMS


Lactated Ringer's (Lactated Ringers Solution)  1,000 mls @ 125 mls/hr IV ASDIR

VICTOR M


   Last Admin: 07/07/20 12:41 Dose:  125 mls/hr




Sodium Chloride (Normal Saline -)  1,000 mls @ 50 mls/hr IV ASDIR Atrium Health Harrisburg


   Stop: 07/07/20 16:14


   Last Admin: 07/06/20 21:03 Dose:  50 mls/hr




Losartan Potassium (Cozaar -)  25 mg PO DAILY Atrium Health Harrisburg


   Last Admin: 07/07/20 09:09 Dose:  25 mg




Serenazaradne (Remeron -)  7.5 mg PO HS VICTOR M


   Last Admin: 07/06/20 21:01 Dose:  7.5 mg




Ondansetron HCl (Zofran Injection)  4 mg IVPUSH Q6H PRN


   PRN Reason: NAUSEA AND/OR VOMITING


Oxycodone HCl (Roxicodone -)  10 mg PO Q4H PRN


   PRN Reason: PAIN LEVEL 6-10


   Last Admin: 07/07/20 01:59 Dose:  10 mg




Oxycodone HCl (Roxicodone -)  5 mg PO Q4H PRN


   PRN Reason: PAIN LEVEL 1-5
















Patient is a 78 year old female with history of dementia, hypertension, spinal

stenosis s/p removal of L3-L5 hardware, including L4-L5 intervertebral cage, L3-

S1 laminectomy, L5-S1 PLIF, L3-S1 posterior instrumented spinal fusion. Post-op

day #1. Surgical site clean, dry and intact.





Neurologic


History of dementia, depression


 -Continue home Mirtazapine, Citalopram


 -Monitor for signs of mental status changes





Pulmonary


 -Currently saturating well, without respiratory distress.


 -Incentive spirometer q15 minutes


 -Monitor for change in oxygen requirements, respiratory distress





Cardiovascular


History of hypertension


 -Losartan 25mg PO daily


 -Labetalol 10mg IV push for systolic BP greater than 160mmHg





Musculoskeletal


S/P removal of L3-L5 hardware, including L4-L5 intervertebral cage, L3-S1



 -Pain control with Oxycodone, Morphine. NO NSAIDs per orthopedic surgery


 -Physical therapy consult


-Orthopedic surgery evaluated pt. Recommends OOB to chair. Advance diet to

clears if tolerated.





Gastrointestinal


 -NPO until patient is passing flatus


 -Gentle hydration with IV normal saline at 50mL/ hour





ID


-WBC 23.4, afebrile. Will continue to trend. If uptrending WBC and febrile, will

send blood cx, urine cx, UA.


-If diarrhea, will send stool for C. diff.





FEN


-Lactated ringers 125 ml/hr


-NS at 50 mL/hr


-Advance diet to clears if tolerated.


-Mg 1.5, repleted. Will follow and replete if depleted.





Prophylaxis


 -SCDs bilateral lower extremities





Disposition: continue ICU monitoring.








Visit type





- Emergency Visit


Emergency Visit: Yes


ED Registration Date: 07/06/20


Care time: Armida dodsonient presented to the Emergency Department on the above date

and was hospitalized for further evaluation of their emergent condition.





- New Patient


This patient is new to me today: No





- Critical Care


Critical Care patient: Yes


Total Critical Care Time (in minutes): 38


Critical Care Statement: The care of this patient involved high complexity

decision making to prevent further life threatening deterioration of the

patient's condition and/or to evaluate & treat vital organ system(s) failure or

risk of failure.

--- PN — 2020-07-08 09:16 ---
  [PN] Physical Exam:


SUBJECTIVE: Patient seen and examined. No acute overnight events. Stated that

her pain is improved this morning.








OBJECTIVE:





                                   Vital Signs











 Period  Temp  Pulse  Resp  BP Sys/Hadley  Pulse Ox





 Last 24 Hr  97.7 F-98.7 F  67-87  15-25  130-150/54-70  100











GENERAL: The patient is awake, alert, and fully oriented, in no acute distress.


HEAD: Normal with no signs of trauma.


EYES: PERRL, extraocular movements intact, sclera anicteric, conjunctiva clear.

No ptosis.


ENT: Ears normal, nares patent, oropharynx clear without exudates, moist mucous


membranes.


NECK: Trachea midline, full range of motion, supple.



## Step 3 — Ground truth

In [16]:
display(Markdown("**Ground truth (not shown to either model):**"))
print(case["ground_truth"])

**Ground truth (not shown to either model):**

## Step 4 — Opus 4.7 response

In [17]:
display(Markdown("**Opus 4.7 response:**"))
print(case["opus_response"])
display(Markdown(f"**Opus scores:** Sonnet={case['opus_score_sonnet']}, GPT-mini={case['opus_score_gpt_mini']}, Gemini={case['opus_score_gemini']}, mean={case['opus_score_mean']}"))

**Opus 4.7 response:**

# Lab Summary

**Patient:** 78yo female, prolonged admission post lumbar spine surgery complicated by sepsis, wound infection, CVA, and severe malnutrition.

## Abnormal Lab Values & Recommended Actions

### Hematology

| Abnormality | Value | Clinical Action |
|---|---|---|
| **Leukocytosis** | WBC up to 23.4 (peak), persistently 12–20 H | Trend CBC; obtain blood/urine/wound cultures if febrile o

**Opus scores:** Sonnet=0.75, GPT-mini=0.0, Gemini=0.33, mean=0.36

### Per-judge evaluation of Opus 4.7's response

In [18]:
display(render_judge_eval(case["criteria"], "claude-opus-4-7", scope="rubric"))

### Universal criteria (Opus)

In [19]:
display(render_judge_eval(case["criteria"], "claude-opus-4-7", scope="universal"))

## Step 5 — GPT-5.5 response

In [20]:
display(Markdown("**GPT-5.5 response:**"))
print(case["gpt55_response"])
display(Markdown(f"**GPT-5.5 scores:** Sonnet={case['gpt55_score_sonnet']}, GPT-mini={case['gpt55_score_gpt_mini']}, Gemini={case['gpt55_score_gemini']}, mean={case['gpt55_score_mean']}"))

**GPT-5.5 response:**

### Overall lab summary
Labs show a prolonged postoperative inflammatory/infectious course with **persistent leukocytosis**, **anemia**, **reactive thrombocytosis**, and **severe protein-calorie malnutrition/hypoalbuminemia**. There were intermittent electrolyte abnormalities and mild liver enzyme abnormalities. Cultures documented **Pseudomonas UTI**, **E. coli bacteremia**, and polymicrobial spi

**GPT-5.5 scores:** Sonnet=1.0, GPT-mini=1.0, Gemini=0.5, mean=0.83

### Per-judge evaluation of GPT-5.5's response

In [21]:
display(render_judge_eval(case["criteria"], "gpt-5.5", scope="rubric"))

### Universal criteria (GPT-5.5)

In [22]:
display(render_judge_eval(case["criteria"], "gpt-5.5", scope="universal"))

## Step 6 — Rubric definition (what the judges graded against)

In [23]:
display(render_rubric_definition(case["rubric_criteria"], case["rubric_max_positive"]))

## Step 7 — Comparative scoring summary

In [24]:
summary = pd.DataFrame({
    "Opus 4.7": [case["opus_score_sonnet"], case["opus_score_gpt_mini"], case["opus_score_gemini"], case["opus_score_mean"]],
    "GPT-5.5":  [case["gpt55_score_sonnet"], case["gpt55_score_gpt_mini"], case["gpt55_score_gemini"], case["gpt55_score_mean"]],
}, index=["Sonnet judge", "GPT-mini judge", "Gemini judge", "Mean"]).round(2)
display(Markdown("**Scores per (Model Under Testing × judge) and overall mean:**"))
display(summary)

**Scores per (Model Under Testing × judge) and overall mean:**

                Opus 4.7  GPT-5.5
Sonnet judge        0.75     1.00
GPT-mini judge      0.00     1.00
Gemini judge        0.33     0.50
Mean                0.36     0.83

---

# Case 3 — _(populated at runtime from the loaded artifact)_

The case selection rationale is in the artifact JSON. We chose 3 contrasting cases (one easy, one mixed, one hard) to ground the abstract scores.

## Step 1 — Case metadata

In [25]:
case = cases[2]
display(Markdown(f'''
| Field | Value |
|---|---|
| Encounter ID | `{case["encounter_id"]}` |
| PSI code | **{case["psi_code"]}** |
| PSI label | **{case["label"]}** |
| Primary diagnosis | {case.get("primary_dx", "N/A")} ({case.get("primary_dx_desc", "")}) |
| Complexity tier | {case.get("complexity_tier", "?")} |
| LOS bucket | {case.get("los_bucket", "?")} |
| LOS days | {case.get("los_days", "?")} |
| Age / Sex | {case.get("age", "?")}yo {case.get("gender", "?")} |
| Prompt run | **{case["prompt_id"]}** |
'''))

| Field | Value |
|---|---|
| Encounter ID | `AF2F9446-3BF7-4F2D-9BA0-CC244533F849` |
| PSI code | **PSI_14_WOUND_DEHISCENCE** |
| PSI label | **negative** |
| Primary diagnosis | T81.31XA (WOUND DEHISCENCE, SURGICAL, INITIAL ENCOUNTER) |
| Complexity tier | medium |
| LOS bucket | short |
| LOS days | 2 |
| Age / Sex | 68yo MALE |
| Prompt run | **C1** |

## Step 2 — Prompt + rendered input

In [26]:
display(Markdown("**Prompt text sent to both Models Under Testing:**"))
print(case["prompt_text"])
print()
display(Markdown("**Rendered input (what both models saw):**"))
print(f"Length: {len(case['rendered_input']):,} chars (~{len(case['rendered_input'])//4:,} tokens)")
print()
print(case["rendered_input"])

**Prompt text sent to both Models Under Testing:**

Summarize the Assessment and Plan from the admission H&P below. Cover all problems and their plans. Specify the date of the note. Limit your summary to that note only.

**Rendered input (what both models saw):**

Length: 2,432 chars (~608 tokens)

--- H&P — 2022-09-20 22:23 ---
  [H&P] Individualized Treatment Plan   Cardiac Rehab Individual Treatment Plan  Initial/Reassessment/Discharge Assessment/ ReAssessment/ Discharge: 30 day 19 Session #     8   MRN: 3863537 Allergies: Other environmental and Other food   Patient Name: Gerson Small : 1932 Risk Stratification: High    Diagnoses:   1. ST elevation myocardial infarction (STEMI), unspecified artery (HCC)     Age: 86 y.o. Physician: Meagan Darling M.D.    Date of Event: 19 Specialist: Dr. Clover Cronin   Risk Factors:  Hypertension, Hyperlipidemia, Sedentary Lifestyle, Age, Male > 45   Exercise Nutrition Other Core Components/ Risk Factors Psychosocial   Stages of change Stages of change Stages of change Stages of change   Preparation Preparation Preparation Preparation   Fitness Test Lipids Learning Barriers Plan   DASI:  (n/a) Available: No new Learning Barriers: Vision, Hearing, Ready to Learn Psychosocial Plan: Yes   DIST:  (assessed pre- and post-program) Date: 19 Family Support Intervention   Max HR:  (assessed pre- and post-program) Total: 87 mg/dL Yes Behavioral Health Consult: Yes   RPE:  (assessed pre- and post-program) Tri mg/dL Lives: Spouse Physician Referral: No   SPO2:  (assessed pre- and post-program) HDL: 18 mg/dL Other Risk Factors Plan Identifies Stressors: Yes   MET:  (assessed pre- and post-program) LDL: 57 mg/dL Other Risk Factors/Plan: Yes Drug Intervention: N/A   EF= 60 Diabetes Tobacco Use Outcome Survey Tools   Ambulatory Status Diabetes: No History   Smoking Status   • Former Smoker   • Packs/day: 2.50   • Years: 30.00   • Types: Cigarettes   • Quit date: 1980   Smokeless Tobacco   • Former User   • Types: Chew     Comment: chewing tobacco    FP QOL Overall Score:  (assessed pre- and post-program)   Fall Risk Assessed: Yes HbA1C: 6 % Date: 19 Smoking Intervention PHQ-9:  (assessed pre- and post-program)   Exercise Ambulatory Status Assist Devices: Cane (uses oxygen
Systems  Negative    Physical Exam    Vital Signs  Blood Pressure : 115/59   Temperature: 36.3 °C (97.4 °F)   Pulse: 63   Respiration: 18   Pulse Oximetry: 99 %     Partial wound dehiscence at distal aspect of incision tracking to patella tendon    Labs:                    Radiology:  No orders to display         Assessment/Plan:  Pre-Op Diagnosis Codes:     * Wound dehiscence, surgical, initial encounter [T81.31XA]  Procedure(s):  Debridement of right knee with possible revision wound closure

## Step 3 — Ground truth

In [27]:
display(Markdown("**Ground truth (not shown to either model):**"))
print(case["ground_truth"])

**Ground truth (not shown to either model):**

Yes   DIST:  (assessed pre- and post-program) Date: 19 Family Support Intervention   Max HR:  (assessed pre- and post-program) Total: 87 mg/dL Yes Behavioral Health Consult: Yes   RPE:  (assessed pre- and post-program) Tri mg/dL Lives: Spouse Physician Referral: No   SPO2:  (assessed pre- and post-program) HDL: 18 mg/dL Other Risk Factors

## Step 4 — Opus 4.7 response

In [28]:
display(Markdown("**Opus 4.7 response:**"))
print(case["opus_response"])
display(Markdown(f"**Opus scores:** Sonnet={case['opus_score_sonnet']}, GPT-mini={case['opus_score_gpt_mini']}, Gemini={case['opus_score_gemini']}, mean={case['opus_score_mean']}"))

**Opus 4.7 response:**

# Assessment and Plan Summary — H&P Note dated 2022-09-20 22:23

**Pre-Op Diagnosis:**
- Wound dehiscence, surgical, initial encounter (T81.31XA) — partial wound dehiscence at distal aspect of incision tracking to patella tendon (right knee).

**Plan / Procedure:**
- Debridement of right knee with possible revision wound closure.

**Additional context noted in the document:**
- Patient is an 86-ye

**Opus scores:** Sonnet=0.0, GPT-mini=0.0, Gemini=0.0, mean=0.0

### Per-judge evaluation of Opus 4.7's response

In [29]:
display(render_judge_eval(case["criteria"], "claude-opus-4-7", scope="rubric"))

### Universal criteria (Opus)

In [30]:
display(render_judge_eval(case["criteria"], "claude-opus-4-7", scope="universal"))

## Step 5 — GPT-5.5 response

In [31]:
display(Markdown("**GPT-5.5 response:**"))
print(case["gpt55_response"])
display(Markdown(f"**GPT-5.5 scores:** Sonnet={case['gpt55_score_sonnet']}, GPT-mini={case['gpt55_score_gpt_mini']}, Gemini={case['gpt55_score_gemini']}, mean={case['gpt55_score_mean']}"))

**GPT-5.5 response:**

**Admission H&P Date: 2022-09-20**

**Assessment/Plan:**
- **Right knee surgical wound dehiscence** (partial dehiscence at distal incision tracking to patellar tendon): Plan for **debridement of the right knee with possible revision wound closure**.

**GPT-5.5 scores:** Sonnet=0.0, GPT-mini=0.0, Gemini=0.0, mean=0.0

### Per-judge evaluation of GPT-5.5's response

In [32]:
display(render_judge_eval(case["criteria"], "gpt-5.5", scope="rubric"))

### Universal criteria (GPT-5.5)

In [33]:
display(render_judge_eval(case["criteria"], "gpt-5.5", scope="universal"))

## Step 6 — Rubric definition (what the judges graded against)

In [34]:
display(render_rubric_definition(case["rubric_criteria"], case["rubric_max_positive"]))

## Step 7 — Comparative scoring summary

In [35]:
summary = pd.DataFrame({
    "Opus 4.7": [case["opus_score_sonnet"], case["opus_score_gpt_mini"], case["opus_score_gemini"], case["opus_score_mean"]],
    "GPT-5.5":  [case["gpt55_score_sonnet"], case["gpt55_score_gpt_mini"], case["gpt55_score_gemini"], case["gpt55_score_mean"]],
}, index=["Sonnet judge", "GPT-mini judge", "Gemini judge", "Mean"]).round(2)
display(Markdown("**Scores per (Model Under Testing × judge) and overall mean:**"))
display(summary)

**Scores per (Model Under Testing × judge) and overall mean:**

                Opus 4.7  GPT-5.5
Sonnet judge         0.0      0.0
GPT-mini judge       0.0      0.0
Gemini judge         0.0      0.0
Mean                 0.0      0.0

---

# What this notebook is for

Each of the 3 cases above shows the full clinical record the models actually saw, side-by-side responses from Opus 4.7 and GPT-5.5, the structured ground truth, and the per-judge per-criterion scoring with rationales.

This grounds the headline numbers in `wednesday_main.ipynb` (mean scores, plots) in concrete clinical examples. Anyone who asks *"what does a 0.3 score actually mean?"* can flip to one of these cases and see exactly what the model said and why each judge graded it the way they did.